"""Video captioning agent package."""

from ._env import load_env_file
from .contracts import (
    CanonicalVideoReport,
    FrameSample,
    TaskResult,
    VideoMetadata,
    VideoTask,
)
from .cvr_client import (
    CVR_SYSTEM_PROMPT,
    CVR_USER_PROMPT_TEMPLATE,
    DEFAULT_VISION_TIMEOUT_SECONDS,
    FIREWORKS_URL,
    VISION_MAX_TOKENS,
    VISION_MODEL_ID,
    VISION_TEMPERATURE,
    CvrGenerationError,
    FireworksCvrClient,
    build_cvr_request,
)
from .cvr_parser import (
    CvrParseFailure,
    CvrParseFailureKind,
    CvrParseResult,
    parse_cvr_response,
)
from .caption_validation import (
    LONG_CAPTION_WORD_WARNING_THRESHOLD,
    CaptionValidationFailure,
    CaptionValidationFailureKind,
    CaptionValidationResult,
    validate_all_captions,
)
from .deployment_manager import (
    DEFAULT_PROVISION_POLL_INTERVAL_SECONDS,
    DEFAULT_PROVISION_TIMEOUT_SECONDS,
    DeploymentProvisioningError,
    DeploymentRef,
    FireworksDeploymentManager,
    resolve_vision_model_id,
)
from .input_loader import InputLoadResult, load_tasks
from .downloader import (
    DEFAULT_DOWNLOAD_TIMEOUT_SECONDS,
    DownloadFailure,
    DownloadFailureKind,
    DownloadResult,
    download_video,
)
from .frame_sampler import FrameSamplingError, sample_frames
from .style_generator import (
    CaptionGenerationFailure,
    CaptionGenerationResult,
    DEFAULT_STYLE_TIMEOUT_SECONDS,
    STYLE_MAX_TOKENS,
    STYLE_MODEL_ID,
    STYLE_SYSTEM_PROMPT,
    STYLE_TEMPERATURE,
    FireworksStyleClient,
    StyleCaptionClient,
    StyleGenerationError,
    build_style_request,
    generate_all_captions,
)
from .styles import (
    SUPPORTED_STYLES,
    STYLE_OUTPUT_KEYS,
    StyleSelection,
    TaskProcessingOutcome,
    determine_task_eligibility,
    filter_supported_styles,
)
from .result_writer import OUTPUT_RESULTS_PATH, build_task_result, write_results
from .video_inspection import (
    VideoInspectionFailure,
    VideoInspectionFailureKind,
    VideoInspectionResult,
    inspect_video,
)

__all__ = [
    "CanonicalVideoReport",
    "CaptionValidationFailure",
    "CaptionValidationFailureKind",
    "CaptionValidationResult",
    "CVR_SYSTEM_PROMPT",
    "CVR_USER_PROMPT_TEMPLATE",
    "CvrGenerationError",
    "CvrParseFailure",
    "CvrParseFailureKind",
    "CvrParseResult",
    "DEFAULT_PROVISION_POLL_INTERVAL_SECONDS",
    "DEFAULT_PROVISION_TIMEOUT_SECONDS",
    "DEFAULT_VISION_TIMEOUT_SECONDS",
    "DEFAULT_DOWNLOAD_TIMEOUT_SECONDS",
    "DEFAULT_STYLE_TIMEOUT_SECONDS",
    "DeploymentProvisioningError",
    "DeploymentRef",
    "DownloadFailure",
    "DownloadFailureKind",
    "DownloadResult",
    "FIREWORKS_URL",
    "FireworksCvrClient",
    "FireworksDeploymentManager",
    "FrameSamplingError",
    "FireworksStyleClient",
    "FrameSample",
    "InputLoadResult",
    "LONG_CAPTION_WORD_WARNING_THRESHOLD",
    "OUTPUT_RESULTS_PATH",
    "SUPPORTED_STYLES",
    "STYLE_OUTPUT_KEYS",
    "StyleSelection",
    "CaptionGenerationFailure",
    "CaptionGenerationResult",
    "StyleCaptionClient",
    "StyleGenerationError",
    "STYLE_MAX_TOKENS",
    "STYLE_MODEL_ID",
    "STYLE_SYSTEM_PROMPT",
    "STYLE_TEMPERATURE",
    "TaskResult",
    "TaskProcessingOutcome",
    "VideoMetadata",
    "VideoInspectionFailure",
    "VideoInspectionFailureKind",
    "VideoInspectionResult",
    "VideoTask",
    "VISION_MAX_TOKENS",
    "VISION_MODEL_ID",
    "VISION_TEMPERATURE",
    "build_cvr_request",
    "build_task_result",
    "build_style_request",
    "parse_cvr_response",
    "load_tasks",
    "determine_task_eligibility",
    "download_video",
    "sample_frames",
    "filter_supported_styles",
    "generate_all_captions",
    "resolve_vision_model_id",
    "validate_all_captions",
    "write_results",
    "inspect_video",
    "load_env_file",
]
